on: [push]

jobs:
    tree:
        runs-on: ubuntu-latest
        name: readme-tree
        steps:
            - uses: actions/checkout@v3
            - name: Tree
              uses: RavelloH/readme-tree@latest
            - name: commit
              continue-on-error: True
              run: |
                  git init
                  git pull
                  git config --local user.email "dr_hamilton@foxmail.com"
                  git config --local user.name "Ravello-H"
                  git add .
                  git commit -m "[Readme-Tree]`date '+%Y-%m-%d %H:%M:%S'`" || exit
                  git status
                  git push -f
